# Folder where the analysis structure will be created
wdir=/scratch_isilon/groups/dat/apps/MVPGermline/PIPEVER/TEST
# Experiment is from CNAG production [yes|no]
cnagProd=no
# BAM from consensus reads instead of standard production BAMs
consensus=no
# Analysis ID (Subproject name as appears in LIMS if cnagProd=yes)
analysisId=TEST_GRCh38
# Sample sheet in case cnagProd=no
# Format tsv: #pedigree barcode sampleName sex[1(male)|2(female)] sampleStatus[1(unaffected)|2(affected)|-9(NA)] subproject app[WGS|CaptureKitName] motherId[barcode|-9(NA)] fatherId[barcode|-9(NA)] BAMorCRAM GVCForNA VCForNA)
# Header: #pedigree	barcode	sampleName	sex	sampleStatus	subproject	app	motherId	fatherId	bamcram	gvcf	vcf
# bamcram format: absolute path to BAM or CRAM
# gvcf format: absolute path to gVCF by chr (file name: *.CHRNAME.*.g.vcf.gz) or NA if not available
# vcf format: absolute path to VCF by chr (file name: *.CHRNAME.*.vcf.gz) or NA if not available
sampleSheet=/scratch_isilon/groups/dat/apps/MVPGermline/PIPEVER/TEST/TEST_GRCh38.sampleSheet.tsv
# Pipeline configuration file (found at /scratch_isilon/groups/dat/apps/MVPGermline/PIPEVER/conf)
pipeConf=hsapiens.GRCh38.conf
# Candidate genes configuration (found at /scratch_isilon/groups/dat/apps/MVPGermline/Candidate_Genes)
candidateGenes=ACMG.snpEff_v5_2.genes.GRCh38.mane.1.2.refseq.conf
