#! /usr/bin/env perl
use strict;
use warnings;
use Template qw( );
use experimental 'smartmatch';
use Carp;
use Cwd;
use Getopt::Long;
use List::Util qw(sum);
use File::Basename;
use File::Path;
use POSIX qw(strftime);

my($input,$prefix,$readGroup,$experiment,$covn,$report,$output,$mappability,$countType,$rmDup,$baseQ,$mapQ,$help);	

my $getOpt = GetOptions(
	"i|input:s" => \$input,
	"p|prefix:s" => \$prefix,
	"rg|readGroup:s" => \$readGroup,
	"x|experiment:s" => \$experiment,
	"cn|covN:s" => \$covn,
	"m|mappability:s" => \$mappability,
	"ct|countType:s" => \$countType,
	"rd|rmDup:s" => \$rmDup,
	"bq|minBaseQ:s" => \$baseQ,
	"mq|minMapQ:s" => \$mapQ,
	"o|output:s" => \$output,
	"h|help:s" => \$help);
			
my $usage = qq/
Usage:  getCovMetrics <options>
Options:
	-i, -input		REQ	FILE	Histogram file ([BARCODE].[sample|library].hist) generated by <getCovHist.pl> script
	-p, -prefix		REQ	STR	Sample barcode, library barcode or mapping ID of interest (should match the barcode in the GATK DepthOfCoverage output file)
	-rg, -readGroup		REQ	STR	Read group type [sample | library]
	-x, -experiment		REQ	STR	Type of experiment [wgs | target]
	-cn, -covN		REQ	CSV	Coverage thresholds to get percentage of bases with coverage equal or higher than N
	-m, -mappability	REQ	BOOL	Mappability has been taken into account [75 | 100 | 150 | F]
	-ct, -countType		REQ	STR	How coverage will be computed [COUNT_READS | COUNT_FRAGMENTS]
	-rd, -rmDup		REQ	STR	Discard duplicates from coverage calculation [T | F]
	-bq, -minBaseQ		REQ	INT	Minimum quality of bases to count towards depth as defined in <getPRODcov coverage> command
	-mq, -minMapQ	REQ	INT	Minimum mapping quality of reads to count towards depth as defined in <getPRODcov coverage> command
	-o, -output		REQ	FILE	Output file (<output>.json will be also created)
	-h, -help		OPT	FLAG	Show this help message and die
	
Description: This comand will compute coverage statistics from histogram generated by <getPRODcov getCovHist> command
\n/ ;
	
exit if (!$getOpt);
die ($usage) if (defined $help);
	
# Test parameters
die ("ERROR: <input> parameter is required\n") if(!defined($input));
die ("ERROR: <prefix> parameter is required\n") if(!defined($prefix));
die ("ERROR: <readGroup> parameter is required\n") if(!defined($readGroup));
die ("ERROR: <experiment> parameter is required\n") if(!defined($experiment));
die ("ERROR: <covN> parameter is required\n") if(!defined($covn));
die ("ERROR: <mappability> parameter is required\n") if(!defined($mappability));
die ("ERROR: <countType> parameter is required\n") if(!defined($countType));
die ("ERROR: <rmDup> parameter is required\n") if(!defined($rmDup));
die ("ERROR: <minBaseQ> parameter is required\n") if(!defined($baseQ));
die ("ERROR: <minMapQ> parameter is required\n") if(!defined($mapQ));
die ("ERROR: <output> parameter is required\n") if(!defined($output));
die ("ERROR: <input> file is not readable [$input]\n") if(!-r $input);
die ("ERROR: Unrecognized <experiment> parameter [$experiment]\n") if($experiment ne "target" && $experiment ne "wgs");
die ("ERROR: Unrecognized <readGroup> parameter [$readGroup]\n") if($readGroup ne "sample" && $readGroup ne "library");
die ("ERROR: Unrecognized <mappability> parameter [$mappability]\n") if($mappability ne "75" && $mappability ne "100" && $mappability ne "150" && $mappability ne "F");
die ("ERROR: Unrecognized <countType> parameter [$countType]\n") if($countType ne "COUNT_READS" && $countType ne "COUNT_FRAGMENTS");
die ("ERROR: Unrecognized <rmDup> parameter [$rmDup]\n") if($rmDup ne "T" && $rmDup ne "F");
die ("ERROR: Unrecognized <covN> parameter [$covn]\n") if ($covn !~ /^[0-9,]*$/);
die ("ERROR: Unrecognized <minBaseQ> parameter [$baseQ]\n") if ($baseQ < 0 || $baseQ > 127);
die ("ERROR: Unrecognized <minMapQ> parameter [$mapQ]\n") if ($mapQ < 0 || $mapQ > 90);

# Define stats variables
my ($size_final, $size_genome, $size_ROI) = (0,0,0);
my ($cov_genome, $cov_ROI) = (0,0);
my ($mean_cov, $median_cov) = (0,0);
my ($specificity, $enrichment);
my ($evenness, $mevenness);
	
# Make dico to store "Cn" values
my @covn = split(/,/, $covn);
my (%covHash);
foreach my $val (@covn) { 
	$covHash{$val} = 0; }
	
if ($experiment eq 'target') {
	# Header of target histogram
	# cov	basesnumber_genome	%_genome	cumulative%_genome	basesnumber_ROI	%_ROI	cumulative%_ROI
	
	# Variables
	my @data;
		
	# Open hist file
	open(HISTFILE, $input) || die ("ERROR: Cannot open getCovMetrics input file <$input>\n");
		
	# Parse the file and get first level statistics
	my $lineHist;
	while ($lineHist = <HISTFILE>) {
		chomp $lineHist;
		push (@data,$lineHist);
		my @line = split ("\t",$lineHist);
		# Get MEDIAN COVERAGE
		if ($line[6] < 0.51) {
			$median_cov = $line[0];	}
		
		# Bases with cov = 0
		if ($line[0] == 0) {
			$size_genome = $line[1];
			$size_ROI = $line[4]; }
		
		# Bases with cov > 0
		if ($line[0] > 0) {
			$size_genome = $size_genome + $line[1];
			$size_ROI = $size_ROI + $line[4];
			
			$cov_genome = $cov_genome + ($line[0] * $line[1]);
			$cov_ROI = $cov_ROI + ($line[0] * $line[4]); }
			
		# Get Cn directly from data when being at the correct line	
		if (exists($covHash{$line[0]})){
			$covHash{$line[0]} = sprintf("%.3f",((1 - ($line[6] - $line[5])) * 100)); }
	}
	close(HISTFILE);
		
	# Calculate MEAN COVERAGE
	$mean_cov = sprintf("%.3f",($cov_ROI / $size_ROI));
	
	# Calculate SPECIFICITY and ENRICHMENT
	my $size_off_ROI = $size_genome - $size_ROI;
	my $cov_off_ROI = $cov_genome - $cov_ROI;
	$specificity = sprintf("%.3f",(($cov_ROI/($cov_ROI + $cov_off_ROI)) * 100));
	if ($cov_off_ROI == 0) { $cov_off_ROI = 1; } # Avoid illegal dision by 0 issue
	if ($size_off_ROI == 0) { $size_off_ROI = 1; } # Avoid illegal dision by 0 issue
	$enrichment = sprintf("%.3f",(($cov_ROI/$cov_off_ROI)/($size_ROI/$size_off_ROI)));
		
	# Go back to the data and calculate EVENNESS and MEDIAN EVENNESS
	my $mean_cov_round = sprintf("%.0f",$mean_cov);
	$evenness = getEvenness($mean_cov_round,$size_ROI,"4",\@data);
	$mevenness = getEvenness($median_cov,$size_ROI,"4",\@data);
	
	$size_final = $size_ROI;
}
		
if ($experiment eq 'wgs') {
	# Header of wgs histogram
	# cov	basesnumber_genome	%_genome	cumulative%_genome
	
	# Variables
	my @data;
	
	# Open hist file
	open(HISTFILE, $input) || die ("ERROR: Cannot open getCovMetrics input file <$input>\n");
	
	# Parse the file and get first level statistics
	my $lineHist;
	while ($lineHist = <HISTFILE>) {
		chomp $lineHist;
		push (@data,$lineHist);
		my @line = split ("\t",$lineHist);
		
		# Get MEDIAN COVERAGE
		if ($line[3] < 0.51) {
			$median_cov = $line[0];	}
			
		# Bases with cov = 0
		if ($line[0] == 0) {
			$size_genome = $line[1];
			$cov_genome = 0; }
		
		# Bases with cov > 0
		if ($line[0] > 0){
			$cov_genome = $cov_genome + ($line[0] * $line[1]);
			$size_genome = $size_genome + $line[1]; }
			
		# Get "Cn" directly from data when being at the correct line
		if (exists($covHash{$line[0]})){
			$covHash{$line[0]} = sprintf("%.3f",((1 - ($line[3] - $line[2])) * 100)); }
	}
	close(HISTFILE);
		
	# Calculate MEAN COVERAGE
	$mean_cov = sprintf("%.3f",($cov_genome / $size_genome));
		
	# Go back to the data and calculate EVENNESS and MEDIAN EVENNESS
	my $mean_cov_round = sprintf("%.0f",$mean_cov);
	$evenness = getEvenness($mean_cov_round,$size_genome,"1",\@data);
	$mevenness = getEvenness($median_cov,$size_genome,"1",\@data);
		
	$specificity = 'NA';
	$enrichment = 'NA';
	
	$size_final = $size_genome;
}
	
# Print results

# Open output files
open (HISTSTATS, ">$output") || die ("ERROR: Cannot open getCovMetrics output file <$output>\n");
open (HISTSTATSJSON, ">$output.json") || die ("ERROR: Cannot open getCovMetrics output file <$output.json>\n");
print (HISTSTATSJSON "{\n");	

# Computation info
# Experiment type
print (HISTSTATS "##Experiment type: $experiment\n");
print (HISTSTATSJSON "\t\"Experiment type\":\"$experiment\",\n");
	
# Genome reference
#~ my ($genomeRef) = $$conf{Fasta} =~ m/^.*\/fasta\/(.*)\.fasta/; 
#~ print (HISTSTATS "##Genome reference: $genomeRef\n");
#~ print (HISTSTATSJSON "\t\"Genome reference\":\"$genomeRef\",\n");
	
# ROI file
#~ if ($experiment eq 'target' && defined($roiType)) {
	#~ my ($ROIFile) = $$conf{$roiType} =~ m/^.*\/target\/(.*\.bed)/; 
	#~ print (HISTSTATS "##ROI BED file: $ROIFile\n");
	#~ print (HISTSTATSJSON "\t\"ROI BED file\":\"$ROIFile\",\n");
#~ }
#~ else {
	#~ print (HISTSTATS "##ROI BED file: NA\n");
	#~ print (HISTSTATSJSON "\t\"ROI BED file\":\"NA\",\n"); }

#~ # Mappability
print (HISTSTATS "##Mappability: 150\n");
print (HISTSTATSJSON "\t\"Mappability\":\"150\",\n");
	
# Count type
print (HISTSTATS "##Count type: $countType\n");
print (HISTSTATSJSON "\t\"Count type\":\"$countType\",\n");

# Count type
print (HISTSTATS "##Discard duplicates: T\n");
print (HISTSTATSJSON "\t\"Discard duplicates\":\"T\",\n");

# BaseQ
print (HISTSTATS "##Minimum base quality: $baseQ\n");
print (HISTSTATSJSON "\t\"Minimum base quality\":\"$baseQ\",\n");
	
# MapQ
print (HISTSTATS "##Minimum mapping quality: $mapQ\n");
print (HISTSTATSJSON "\t\"Minimum mapping quality\":\"$mapQ\",\n");
		
# Header
my $barcodeType = ucfirst($readGroup);
print (HISTSTATS "#$barcodeType\tROI_Size\tMean_cov\tMedian_cov\t");	
foreach my $key (sort {$a <=> $b} keys(%covHash)) {
	print (HISTSTATS "C$key\t"); }
print (HISTSTATS "Evenness\tMedian_Evenness\tSpecificity\tEnrichment\n");
	
# Data
print (HISTSTATS "$prefix\t$size_final\t$mean_cov\t$median_cov\t");
foreach my $key (sort {$a <=> $b} keys(%covHash)) {
	print (HISTSTATS abs($covHash{$key})."\t"); }
print (HISTSTATS "$evenness\t$mevenness\t$specificity\t$enrichment\n");

# Data in json format
print (HISTSTATSJSON "\t\"$barcodeType\":\"$prefix\",\n");
print (HISTSTATSJSON "\t\"ROI_Size\":\"$size_final\",\n");
print (HISTSTATSJSON "\t\"Mean_cov\":\"$mean_cov\",\n");
print (HISTSTATSJSON "\t\"Median_cov\":\"$median_cov\",\n");
foreach my $key (sort {$a <=> $b} keys(%covHash)) {
	print (HISTSTATSJSON "\t\"C$key\":\"".abs($covHash{$key})."\",\n"); }	
print (HISTSTATSJSON "\t\"Evenness\":\"$evenness\",\n");
print (HISTSTATSJSON "\t\"Median_Evenness\":\"$mevenness\",\n");
print (HISTSTATSJSON "\t\"Specificity\":\"$specificity\",\n");
print (HISTSTATSJSON "\t\"Enrichment\":\"$enrichment\"\n");
	
close(HISTSTATS);
print (HISTSTATSJSON "}\n");
close(HISTSTATSJSON);


# SUB FUNCTIONS
sub getEvenness {
	
	my ($cov,$size,$histBaseNumberIndex,$data) = @_;
	my $evenness;
	if ($cov < 1) {
		$evenness = 'NA';	}
	else {
		my $pi = 0;
		for my $i (1 .. $cov) {
			foreach (@{$data}) {
				my @line = split ("\t",$_);
				if ($line[0] >= $i) {
					$pi = $pi + $line[$histBaseNumberIndex]; }
			}
		}
		$evenness = sprintf("%.3f",( ( $pi/($cov*$size) )*100) );
	}
	return $evenness;
}
