bindDir='/scratch_isilon,/shared'
annotsvCont="annotsv_3.4.4.sif"
bcftoolsCont="bcftools_v1.21.sif"
bedtoolsCont="bedtools_2.30.0.sif"
gatk4Cont="gatk_4.1.9.0.sif"
htslibCont="htslib_1.15.1.sif"
igvReportCont="igvreports_1.14.1.sif"
mosdepthCont="mosdepth_0.3.3.sif"
perlCont="perl_5.30.3.sif"
picardCont="picard_2.26.10.sif"
samtoolsCont="samtools_1.15.1.sif"
biobambamCont="biobambam_2.0.179.sif"
snpeffCont="snpeff_5.4.sif"
snpsiftCont="snpsift_5.4.sif"
somalierCont="somalier_0.3.1.sif"
exdepthCont="exomedepth_1.1.17.sif"
smafindCont="sma_finder_1.4.4.sif"
smncallCont="smncopynumbercaller_1.1.2.sif"
vcf2tabCont="vcf2tabular_1.0.1.sif"
intervarCont="intervar_2.2.1.sif"
plinkCont="plink_1.90.sif"
spliceaiCont="spliceai_1.3.1.sif"
mtgatkCont="gatk_4.1.7.0.sif"
mtgenomeCont="genomes-in-the-cloud_2.4.2-1552931386.sif"
mthaploCont="haplochecker_haplochecker-0124.sif"
freecCont="control_freec_11.5.sif"
clinsvCont="clinsv_1.0.sif"
cyriusCont="cyrius_1.1.1.sif"
gauchianCont="gauchian_1.0.2.sif"
pypgxCont="pypgx_0.25.0.sif"
stripyCont="stripy_2.5cnag.sif"
t1kCont="t1k_1.0.8.sif"
casesummCont="casesummarizer_2.0.6.sif"
cramtoolsCont="cramtoolscnag_1.0.4.sif"
