roiBed="/shared/pbt/targetcapture/Kapa_HyperExome_mt/Kapa.HyperExome.mt_hsapiens.hg38_captureTarget.merge.bed"
bedPadding="0|10|50"
exdepthRef="hg38"
exdepthPath="/scratch_isilon/groups/dat/data/CNV/ExomeDepth/EDobject/GRCh38/KAPA_HyperExome_mt"
freecMaleBase="/scratch_isilon/groups/dat/data/CNV/Baseline_for_CNV/HyperExome/HyperExome.GRCh38.hl.male.baseline.100x.bam"
freecFemaleBase="/scratch_isilon/groups/dat/data/CNV/Baseline_for_CNV/HyperExome/HyperExome.GRCh38.hl.female.baseline.100x.bam"
freecChrLen="/scratch_isilon/groups/dat/apps/FREEC/GRCh38.hl_chr.len"
freecChrDir="/scratch_isilon/groups/dat/apps/FREEC/GRCh38"
freecPloidy=2
freecMappa="/scratch_isilon/groups/dat/apps/FREEC/hsapiens.GRCh38.hl_l100_m2_GEM1.map"
freecSnpfile="/scratch_isilon/groups/dat/apps/FREEC/hg38_chr_snp150.SingleDiNucl.1based.txt"
freecMakepileup="/scratch_isilon/groups/dat/apps/FREEC/hg38_chr_snp150.SingleDiNucl.bed"
freecBed="/shared/pbt/targetcapture/Kapa_HyperExome/Kapa.HyperExome_hsapiens.hg38_captureTarget.merge.bed"
