roiBed="/shared/pbt/targetcapture/SureSelect_Human_All_Exon_v6r2_UTRs_S07604624/SureSelect.Human.All.Exon.v6r2.UTRs.S07604624_hsapiens.hg38_captureTarget.merge.bed"
bedPadding="0|10|50"
exdepthRef="hg38"
exdepthPath="/scratch_isilon/groups/dat/data/CNV/ExomeDepth/EDobject/GRCh38/SureSelect.Human.All.Exon.v6r2.UTRs.S07604624"
freecMaleBase="NA"
freecFemaleBase="NA"
freecChrLen="NA"
freecChrDir="NA"
freecPloidy=2
freecMappa="NA"
freecSnpfile="NA"
freecMakepileup="NA"
freecBed="NA"
