roiBed="/shared/pbt/targetcapture/SureSelect_Human_All_Exon_v6r2_S07604514/SureSelect.Human.All.Exon.v6r2.S07604514_hsapiens.GRCh38.hl_captureTarget.merge.bed"
bedPadding="0|10|50"
exdepthRef="NA"
exdepthPath="NA"
freecMaleBase="NA"
freecFemaleBase="NA"
freecChrLen="NA"
freecChrDir="NA"
freecPloidy=2
freecMappa="NA"
freecSnpfile="NA"
freecMakepileup="NA"
freecBed="NA"
