roiBed="NA"
bedPadding="NA"
exdepthRef="NA"
exdepthPath="NA"
freecMaleBase="/scratch_isilon/groups/dat/data/CNV/Baseline_for_CNV/WholeGenome/WholeGenome.GRCh38.hl.male.baseline.30x.bam"
freecFemaleBase="/scratch_isilon/groups/dat/data/CNV/Baseline_for_CNV/WholeGenome/WholeGenome.GRCh38.hl.female.baseline.30x.bam"
freecChrLen="/scratch_isilon/groups/dat/apps/FREEC/GRCh38.hl_chr.len"
freecChrDir="/scratch_isilon/groups/dat/apps/FREEC/GRCh38"
freecPloidy=2
freecMappa="/scratch_isilon/groups/dat/apps/FREEC/hsapiens.GRCh38.hl_l100_m2_GEM1.map"
freecSnpfile="/scratch_isilon/groups/dat/apps/FREEC/hg38_chr_snp150.SingleDiNucl.1based.txt"
freecMakepileup="/scratch_isilon/groups/dat/apps/FREEC/hg38_chr_snp150.SingleDiNucl.bed"
freecBed="NA"
