roiBed="/shared/pbt/targetcapture/Kapa_HyperExome_v2/Kapa.HyperExome.v2_hsapiens.hg38_captureTarget.merge.bed"
bedPadding="0|10|50"
exdepthRef="hg38"
exdepthPath="/scratch_isilon/groups/dat/data/CNV/ExomeDepth/EDobject/GRCh38/KAPA_HyperExome_v2"
freecMaleBase="NA"
freecFemaleBase="NA"
freecChrLen="NA"
freecChrDir="NA"
freecPloidy=2
freecMappa="NA"
freecSnpfile="NA"
freecMakepileup="NA"
freecBed="NA"
