organism="hsapiens"
fasta="/scratch_isilon/groups/dat/data/Organisms/Homo_sapiens/GRCh38.hl/fasta/hsapiens.GRCh38.hl.fasta"
chrList="chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY chrM"
dbsnp="/scratch_isilon/groups/dat/data/GATK/Bundle/hg38/dbsnp_146.hg38.vcf.gz"
snpeffDb="GRCh38.mane.1.2.refseq"
snpeffConf="/scratch_isilon/groups/dat/apps/SNPEFF/5.2/snpEff.config"
annotToml="/scratch_isilon/groups/dat/apps/MVPGermline/20260109/conf/hsapiens.GRCh38_vcfanno.toml"
greenvRef="GRCh38"
greenvChr=""
intervarDb="hg38"
intervarappendChr="-c chr"
spliceaiDb="grch38"
spliceaiKnown="/scratch_isilon/groups/dat/data/SPLICEAI/1.3/spliceai_annotations_knownSites.hg38.bed"
spliceaiMD="4999"
spliceaiMS="0"
spliceairuncandigene="F"
spliceairuncandigeneDb="grch38"
rohGrep="^chrEBV\|^chrUn\|random"
mantaCallBed="/scratch_isilon/groups/dat/data/BED/excludeRegionsForSV/human.hg38.incl.bed.gz"
annotsvRef="GRCh38"
annotsvDb="RefSeq"
annotsvAnnotDir="/scratch_isilon/groups/dat/apps/ANNOTSV/3.4.4"
annotsvAnnotDirIntFreq="/scratch_isilon/groups/dat/apps/ANNOTSV/3.4.4_IMPACT"
annotsvAnnotPost="/scratch_isilon/groups/dat/apps/MVPGermline/20260109/AnnotsvIntFreq.sh"
var2trackFreec="varconvert2track_FREEC_GRCh38.json"
var2trackManta="varconvert2track_MANTA_GRCh38.json"
somalierSites="/scratch_isilon/groups/dat/apps/SOMALIER/0.3.1/sites.hg38.vcf.gz"
somalierPath="/scratch_isilon/groups/dat/data/Somalier/GRCh38"
mappaBed="/shared/pbt/mappability/hsapiens.GRCh38.hl_l150_m2_GEM1.map.bed.gz"
genomeBed="/scratch_isilon/groups/pbt/jrtrotta/getPRODcov/genome/hsapiens.GRCh38.hl.gen.bed"
maneBed="/shared/pbt/targetcapture/MANE_v1.4/MANE.GRCh38.v1.4.all.bed"
manePrefix='MANE.GRCh38.v1.4'
mtChr="chrM"
mtGnomad="/scratch_isilon/groups/dat/data/MT/chrM_gnomad.genomes.r3.1.silentFixed.vcf.gz"
mtMitomapDisease="/scratch_isilon/groups/dat/data/MT/chrM_MitoMap_disease.vcf.gz"
mtMitomapPolymorphisms="/scratch_isilon/groups/dat/data/MT/chrM_MitoMap_polymorphisms.vcf.gz"
mtMitoTip="/scratch_isilon/groups/dat/data/MT/chrM_MitoTIP.vcf.gz"
clinsvRef="/scratch_isilon/groups/dat/apps/CLINSV/1.1.0/refdata-b38"
smncallDb="38"
cyriusDb="38"
gauchianDb="38"
pypgxDb="GRCh38"
pypgxBundle=/scratch_isilon/groups/dat/data/PYPGX/pypgx-bundle/
stripyDb="hg38"
stripyCatalog="/scratch_isilon/groups/dat/apps/STRIPY-PIPELINE/2.5/catalog.json"
stripyGene="AFF2,AR,ARX_1,ARX_2,ATN1,ATXN1,ATXN10,ATXN2,ATXN3,ATXN7,ATXN8OS,BEAN1,C9ORF72,CACNA1A,CBL,CNBP,COMP,DAB1,DIP2B,DMD,DMPK,FGF14,FMR1,FOXL2,FXN,GIPC1,GLS,HOXA13_1,HOXA13_2,HOXA13_3,HOXD13,HTT,JPH3,LRP12,MARCHF6,NIPA1,NOP56,NOTCH2NLC,NUTM2B-AS1,PABPN1,PHOX2B,PPP2R2B,PRDM12,RAPGEF2,RFC1,RILPL1,RUNX2,SAMD12,SOX3,STARD7,TBP,TBX1,TCF4,TNRC6A,XYLT1,YEATS2,ZIC2,ZIC3"
ehshortCatalog="/scratch_isilon/groups/dat/data/EXPANSIONHUNTER/4.0.2/variant_catalog/grch38/variant_catalog.json"
ehlongCatalog="/scratch_isilon/groups/dat/data/REPEATCATALOGS/1.0.0/hg38/variant_catalog.json"
mhcRegion="chr6:28510120-33480577"
pgxgenoDir="/scratch_isilon/groups/dat/apps/MVPGermline/PGx_Genotype"
pgxgenoPosVcf="PGx.94_positions.GRCh38.vcf.gz"
pgxgenoPosBed="PGx.94_positions.GRCh38.bed"
pgxgenoPosLabel="PGx.94_positions"
mantaPath="/scratch_isilon/groups/dat/data/Manta/GRCh38"
