roiBed="/shared/pbt/targetcapture/Twist_Exome2.0_comp_mito/Twist.Exome2.0.comp.mito_hsapiens.GRCh38.captureTarget.merge.bed"
bedPadding="0|10|50"
exdepthRef="NA"
exdepthPath="NA"
freecMaleBase="NA"
freecFemaleBase="NA"
freecChrLen="NA"
freecChrDir="NA"
freecPloidy=2
freecMappa="NA"
freecSnpfile="NA"
freecMakepileup="NA"
freecBed="NA"
