custom_logo: "/scratch_isilon/groups/dat/apps/MVPGermline/20260801/cnag_logo.png"
custom_logo_dark: "/scratch_isilon/groups/dat/apps/MVPGermline/20260801/cnag_logo_dark.png"
custom_logo_url: "https://www.cnag.cat"
custom_logo_title: "CNAG"
