pipeVer="20260109"
pipeDir="/scratch_isilon/groups/dat/apps/MVPGermline/${pipeVer}"
ttDir="${pipeDir}/templates"
confDir="${pipeDir}/conf"
contDir="${pipeDir}/containers"
funcDir="${pipeDir}/func"
qcbaselineDir="${pipeDir}/qcbaseline"
geneDir="/scratch_isilon/groups/dat/apps/MVPGermline/Candidate_Genes"
casesummDir="/scratch_isilon/groups/dat/apps/MVPGermline/Case_Summarizer"
