allshortvar_cpu=1
allshortvar_time=00:55:00
allshortvar_mem=1000
allshortvar_qos=vshort

multshortvar_cpu=1
multshortvar_time=00:55:00
multshortvar_mem=1000
multshortvar_qos=vshort

singshortvar_cpu=1
singshortvar_time=00:55:00
singshortvar_mem=1000
singshortvar_qos=vshort

somalier_cpu=1
somalier_time=00:55:00
somalier_mem=1000
somalier_qos=vshort

exdepth_cpu=1
exdepth_time=00:55:00
exdepth_mem=1000
exdepth_qos=vshort

hapcallgenonorm_cpu=4
hapcallgenonorm_time=05:55:00
hapcallgenonorm_mem=8000
hapcallgenonorm_qos=short

combgvcf_cpu=4
combgvcf_time=05:55:00
combgvcf_mem=8000
combgvcf_qos=short

genogvcf_cpu=2
genogvcf_time=00:55:00
genogvcf_mem=8000
genogvcf_qos=vshort

bcfnorm_cpu=2
bcfnorm_time=00:55:00
bcfnorm_mem=8000
bcfnorm_qos=vshort

annotshortvar_cpu=10
annotshortvar_time=23:55:00
annotshortvar_mem=8000
annotshortvar_qos=long

gathervcf_cpu=2
gathervcf_time=05:55:00
gathervcf_mem=8000
gathervcf_qos=short

tagfilt_cpu=4
tagfilt_time=05:55:00
tagfilt_mem=8000
tagfilt_qos=short

hardfilt_cpu=2
hardfilt_time=00:55:00
hardfilt_mem=8000
hardfilt_qos=vshort

reportmake_cpu=2
reportmake_time=00:55:00
reportmake_mem=8000
reportmake_qos=vshort

multmanta_cpu=8
multmanta_time=95:55:00
multmanta_mem=8000
multmanta_qos=marathon

somext_cpu=2
somext_time=05:55:00
somext_mem=8000
somext_qos=short

somrel_cpu=4
somrel_time=05:55:00
somrel_mem=8000
somrel_qos=short

bamtocram_cpu=4
bamtocram_time=23:55:00
bamtocram_mem=8000
bamtocram_qos=long

mosdepth_cpu=4
mosdepth_time=05:55:00
mosdepth_mem=8000
mosdepth_qos=short

singmanta_cpu=8
singmanta_time=118:55:00
singmanta_mem=20000
singmanta_qos=marathon

smafind_cpu=2
smafind_time=00:55:00
smafind_mem=8000
smafind_qos=vshort

smncall_cpu=4
smncall_time=11:55:00
smncall_mem=8000
smncall_qos=normal

vcf2tab_cpu=4
vcf2tab_time=05:55:00
vcf2tab_mem=8000
vcf2tab_qos=short

reportmake_cpu=2
reportmake_time=00:55:00
reportmake_mem=8000
reportmake_qos=vshort

roh_cpu=4
roh_time=00:55:00
roh_mem=8000
roh_qos=vshort

intervarrun_cpu=4
intervarrun_time=720
intervarrun_qos=normal

intervarappend_cpu=4
intervarappend_time=00:55:00
intervarappend_mem=8000
intervarappend_qos=vshort

spliceairun_cpu=4
spliceairun_time=23:55:00
spliceairun_mem=8000
spliceairun_qos=long

spliceairuncandigene_cpu=8
spliceairuncandigene_time=11:55:00
spliceairuncandigene_mem=8000
spliceairuncandigene_qos=normal

spliceaiappend_cpu=2
spliceaiappend_time=00:55:00
spliceaiappend_mem=8000
spliceaiappend_qos=vshort

fakeappend_cpu=1
fakeappend_time=00:55:00
fakeappend_mem=8000
fakeappend_qos=vshort

mt_cpu=4
mt_time=05:55:00
mt_mem=40000
mt_qos=short

clinsv_cpu=8
clinsv_time=47:55:00
clinsv_mem=20000
clinsv_qos=vlong

freecrun_cpu=4
freecrun_time=23:55:00
freecrun_mem=20000
freecrun_qos=long

cyrius_cpu=4
cyrius_time=05:55:00
cyrius_mem=8000
cyrius_qos=short

gauchian_cpu=4
gauchian_time=05:55:00
gauchian_mem=8000
gauchian_qos=short

pypgx_cpu=8
pypgx_time=05:55:00
pypgx_mem=8000
pypgx_qos=short

stripy_cpu=4
stripy_time=11:55:00
stripy_mem=8000
stripy_qos=normal

ehshort_cpu=6
ehshort_time=47:55:00
ehshort_mem=20000
ehshort_qos=vlong

ehlong_cpu=8
ehlong_time=71:55:00
ehlong_mem=8000
ehlong_qos=marathon

hlahd_cpu=4
hlahd_time=00:55:00
hlahd_mem=8000
hlahd_qos=vshort

hlakir_cpu=12
hlakir_time=11:55:00
hlakir_mem=40000
hlakir_qos=normal

t1k_cpu=8
t1k_time=11:55:00
t1k_mem=40000
t1k_qos=normal

igvcram_cpu=4
igvcram_time=47:55:00
igvcram_mem=8000
igvcram_qos=vlong

exdepthprep_cpu=4
exdepthprep_time=00:55:00
exdepthprep_mem=8000
exdepthprep_qos=vshort

exdepthlink_cpu=1
exdepthlink_time=00:55:00
exdepthlink_mem=8000
exdepthlink_qos=vshort

exdepthrun_cpu=4
exdepthrun_time=00:55:00
exdepthrun_mem=8000
exdepthrun_qos=vshort

gutierrezsarprs_cpu=4
gutierrezsarprs_time=05:55:00
gutierrezsarprs_mem=8000
gutierrezsarprs_qos=short

tegerpgxgeno_cpu=4
tegerpgxgeno_time=05:55:00
tegerpgxgeno_mem=8000
tegerpgxgeno_qos=short
