#stepName	stepVar	varCond	checkParam	checkFile	checkDir
singshortvar	dbsnp	no	yes	yes	no
singshortvar	snpeffDb	no	yes	no	no
singshortvar	snpeffConf	snpeffDb	yes	yes	no
singshortvar	annotToml	annotToml	yes	yes	no
singshortvar	greenvRef	no	yes	no	no
singshortvar	intervarDb	no	yes	no	no
singshortvar	spliceaiDb	no	yes	no	no
singshortvar	spliceaiKnown	spliceaiDb	yes	yes	no
singshortvar	spliceaiMD	spliceaiDb	yes	no	no
singshortvar	spliceaiMS	spliceaiDb	yes	no	no
multshortvar	dbsnp	no	yes	yes	no
multshortvar	snpeffDb	no	yes	no	no
multshortvar	snpeffConf	snpeffDb	yes	yes	no
multshortvar	annotToml	annotToml	yes	yes	no
multshortvar	greenvRef	no	yes	no	no
multshortvar	intervarDb	no	yes	no	no
multshortvar	spliceaiDb	no	yes	no	no
multshortvar	spliceaiKnown	spliceaiDb	yes	yes	no
multshortvar	spliceaiMD	spliceaiDb	yes	no	no
multshortvar	spliceaiMS	spliceaiDb	yes	no	no
mt	mtChr	no	yes	no	no
mt	mtGnomad	no	yes	yes	no
mt	mtMitomapDisease	no	yes	yes	no
mt	mtMitomapPolymorphisms	no	yes	yes	no
mt	mtMitoTip	no	yes	yes	no
singmanta	mantaCallBed	no	yes	yes	no
singmanta	annotsvRef	no	yes	no	no
singmanta	annotsvDb	no	yes	no	no
singmanta	annotsvAnnotDir	no	yes	no	yes
multmanta	mantaCallBed	no	yes	yes	no
multmanta	annotsvRef	no	yes	no	no
multmanta	annotsvDb	no	yes	no	no
multmanta	annotsvAnnotDir	no	yes	no	yes
clinsv	clinsvRef	no	yes	no	yes
clinsv	annotsvRef	no	yes	no	no
clinsv	annotsvDb	no	yes	no	no
clinsv	annotsvAnnotDir	no	yes	no	yes
freec	annotsvRef	no	yes	no	no
freec	annotsvDb	no	yes	no	no
freec	annotsvAnnotDir	no	yes	no	yes
exdepth	annotsvRef	no	yes	no	no
exdepth	annotsvDb	no	yes	no	no
exdepth	annotsvAnnotDir	no	yes	no	yes
cyrius	cyriusDb	no	yes	no	no
gauchian	gauchianDb	no	yes	no	no
pypgx	pypgxDb	no	yes	no	no
pypgx	pypgxBundle	no	yes	no	yes
stripy	stripyDb	no	yes	no	no
stripy	stripyCatalog	no	yes	yes	no
stripy	stripyGene	no	yes	no	no
ehshort	ehshortCatalog	no	yes	yes	no
ehlong	ehshortCatalog	no	yes	yes	no
hlahd	mhcRegion	no	yes	no	no
somalier	somalierSites	no	yes	yes	no
mosdepth	mappaBed	no	yes	yes	no
mosdepth	genomeBed	no	yes	yes	no
mosdepth	maneBed	no	yes	yes	no
mosdepth	manePrefix	maneBed	yes	no	no
