#stepName	stepDef	stepSpecie	stepApp	stepResult	stepCond	stepAll
singshortvar	SNVs/INDELs by sample	All species	[WGS|WES]	SNV-InDels	no	yes
mt	GATK Mitochondrial pipeline by sample	Human only	[WGS|WES]	mtDNA	no	yes
roh	Runs of Homozygosity by sample	All species	[WGS|WES]	Homozygosity	no	yes
multshortvar	SNVs/INDELs by pedigree	All species	[WGS|WES]	SNV-InDels	no	yes
allshortvar	SNVs/INDELs without annotation for whole analysis	All species	[WGS|WES]	SNV-InDels	no	no
singmanta	SVs by sample with Manta	All species	[WGS|WES]	Structural_variants	no	yes
multmanta	SVs by pedigree with Manta	All species	[WGS|WES]	Structural_variants	no	yes
clinsv	CNVs by sample with ClinSV	All species	[WGS]	Structural_variants	wgs	yes
exdepth	CNVs by sample with ExomeDetph	All species	[WES]	Structural_variants	wes	yes
freec	CNVs by sample with Control-FREEC	All species	[WGS|WES]	Structural_variants	no	yes
stripy	STRs by sample with Stripy	Human only	[WGS|WES]	ShortTandemRepeats	no	yes
ehshort	STRs by sample with Expansion Hunter on short catalog of variants	Human only	[WGS|WES]	ShortTandemRepeats	no	yes
ehlong	STRs by sample with Expansion Hunter on long catalog of variants	Human only	[WGS|WES]	ShortTandemRepeats	no	yes
smafind	SMA finder by sample	Human only	[WGS|WES]	Pseudogenes	no	yes
smncall	SMN caller by sample	Human only	[WGS|WES]	Pseudogenes	no	yes
cyrius	CYP2D6 by sample	Human only	[WGS|WES]	PharmacoGenomics	no	yes
pypgx	PyPGx by sample	Human only	[WGS|WES]	PharmacoGenomics	no	yes
gauchian	GBA by sample	Human only	[WGS|WES]	Immunology	no	yes
hlahd	MHC by sample with HLA-HD	Human only	[WGS]	Immunology	wgs	yes
hlakir	HLA and KIR by sample with T1K	Human only	[WGS]	Immunology	wgs	yes
somalier	Somalier relate and ancestry by analysis and pedigree	All species	[WGS|WES]	Somalier	no	yes
mosdepth	Coverage by sample	All species	[WGS|WES]	Coverage	no	yes
igvcram	CRAM by sample for IGV visualization	All species	[WGS|WES]	igvCRAM	no	yes
bamtocram	BAM to CRAM convertion by sample	All species	[WGS|WES]	On demand	no	yes
gutierrezsarprs	PRS by sample specific to GUTIERREZSAR project	Human only	[WGS|WES]	PRS	no	no
tegerpgxgeno	PGx genotype by sample specific to TEGER project	Human only	[WGS|WES]	PharmacoGenomics	no	no
