#--------------#
# roh          #
#--------------#
roh	NA	no	all	ANA/PED/STEP/SAMP/SAMP.hom.bed	TRACKDEST/SUBPROJECT/SAMP/SAMP.ROH.bed

#--------------#
# exdepth      #
#--------------#
exdepth	NA	wes	all	ANA/cnv/APP/STEP/SAMP/SAMP.exdepth.annot.tag.tsv	CNVDEST/PROJECT/SUBPROJECT/SUBPROJECT_Results/PED/SAMP/Structural_variants/CNV/ExomeDepth/SAMP.ExomeDepth.CNV.annot.tsv

#--------------#
# freec        #
#--------------#
freec	NA	wgs	all	ANA/PED/STEP/SAMP/20000/SAMP.freec.20000.annot.tag.tsv	CNVDEST/PROJECT/SUBPROJECT/SUBPROJECT_Results/PED/SAMP/Structural_variants/CNV/ControlFreeC_FREECSUF/SAMP.ControlFreeC_FREECSUF.CNV.annot.tsv
freec	NA	wes	all	ANA/PED/STEP/SAMP/0/SAMP.freec.0.annot.tag.tsv	CNVDEST/PROJECT/SUBPROJECT/SUBPROJECT_Results/PED/SAMP/Structural_variants/CNV/ControlFreeC_FREECSUF/SAMP.ControlFreeC_FREECSUF.CNV.annot.tsv
freec	NA	wgsfreectrack	all	ANA/PED/STEP/SAMP/20000/SAMP.freec.20000.annot.tag.full.vcf.gz	TRACKDEST/SUBPROJECT/SAMP/SAMP.CNVs.ControlFreeC.FREECSUF.Full.vcf.gz
freec	NA	wgsfreectrack	all	ANA/PED/STEP/SAMP/20000/SAMP.freec.20000.annot.tag.full.vcf.gz.tbi	TRACKDEST/SUBPROJECT/SAMP/SAMP.CNVs.ControlFreeC.FREECSUF.Full.vcf.gz.tbi
freec	NA	wesfreectrack	all	ANA/PED/STEP/SAMP/0/SAMP.freec.0.annot.tag.full.vcf.gz	TRACKDEST/SUBPROJECT/SAMP/SAMP.CNVs.ControlFreeC.FREECSUF.Full.vcf.gz
freec	NA	wesfreectrack	all	ANA/PED/STEP/SAMP/0/SAMP.freec.0.annot.tag.full.vcf.gz.tbi	TRACKDEST/SUBPROJECT/SAMP/SAMP.CNVs.ControlFreeC.FREECSUF.Full.vcf.gz.tbi

#--------------#
# singmanta    #
#--------------#
singmanta       NA      no      all     ANA/PED/STEP/SAMP/SAMP.manta.annot.tag.tsv      CNVDEST/PROJECT/SUBPROJECT/SUBPROJECT_Results/PED/SAMP/Structural_variants/SV/SAMP.manta.SV.annot.tsv
# TRACKDEST/SUBPROJECT/SAMP/SAMP.SVs.MantaDelly.Union.Full.vcf.gz
singmanta	NA	nvarsmvcf	all	ANA/PED/STEP/SAMP/SAMP.manta.annot.tag.full.vcf.gz	TRACKDEST/SUBPROJECT/SAMP/SAMP.SVs.MantaDelly.Union.Full.vcf.gz
singmanta	NA	nvarsmtbi	all	ANA/PED/STEP/SAMP/SAMP.manta.annot.tag.full.vcf.gz.tbi	TRACKDEST/SUBPROJECT/SAMP/SAMP.SVs.MantaDelly.Union.Full.vcf.gz.tbi

#--------------#
# ehshort      #
#--------------#
ehshort	NA	no	hsapiens	ANA/PED/STEP/SAMP/SAMP.expansionhunter.shortcatalog.vcf.gz	TRACKDEST/SUBPROJECT/SAMP/SAMP.STRs.ExpansionHunter.ShortCatalog.vcf.gz
ehshort	NA	no	hsapiens	ANA/PED/STEP/SAMP/SAMP.expansionhunter.shortcatalog.vcf.gz.tbi	TRACKDEST/SUBPROJECT/SAMP/SAMP.STRs.ExpansionHunter.ShortCatalog.vcf.gz.tbi

#--------------#
# ehlong       #
#--------------#
ehlong	NA	no	hsapiens	ANA/PED/STEP/SAMP/SAMP.expansionhunter.longcatalog.vcf.gz	TRACKDEST/SUBPROJECT/SAMP/SAMP.STRs.ExpansionHunter.LongCatalog.vcf.gz
ehlong	NA	no	hsapiens	ANA/PED/STEP/SAMP/SAMP.expansionhunter.longcatalog.vcf.gz.tbi	TRACKDEST/SUBPROJECT/SAMP/SAMP.STRs.ExpansionHunter.LongCatalog.vcf.gz.tbi

#--------------#
# igvcram      #
#--------------#
igvcram	NA	no	all	ANA/PED/STEP/SAMP/SAMP.igv.cram	IGVDEST/PROJECT/SUBPROJECT/SAMP.igv.cram
igvcram	NA	no	all	ANA/PED/STEP/SAMP/SAMP.igv.cram.crai	IGVDEST/PROJECT/SUBPROJECT/SAMP.igv.cram.crai

