#--------------#
# singshortvar #
#--------------#
singshortvar	gathervcfpreannot	no	all	ANA/PED/SUB/SAMP/SAMP.allchr.g.geno.norm.vcf.gz	SAVE/PED/SAMP	SAMP.allchr.g.geno.norm.vcf.gz
singshortvar	gathervcfpreannot	no	all	ANA/PED/SUB/SAMP/SAMP.allchr.g.geno.norm.vcf.gz.tbi	SAVE/PED/SAMP	SAMP.allchr.g.geno.norm.vcf.gz.tbi

#--------------#
# mt           #
#--------------#
mt	NA	no	hsapiens	ANA/PED/STEP/SAMP/SAMP.MT_GATK.vcf.gz	SAVE/PED/SAMP	SAMP.MT_GATK.vcf.gz
mt	NA	no	hsapiens	ANA/PED/STEP/SAMP/SAMP.MT_GATK.vcf.gz.tbi	SAVE/PED/SAMP	SAMP.MT_GATK.vcf.gz.tbi

#--------------#
# singmanta    #
#--------------#
singmanta	NA	no	all	ANA/PED/STEP/SAMP/results/variants/diploidSV.vcf.gz	SAVE/PED/SAMP	SAMP.manta.diploidSV.vcf.gz
singmanta	NA	no	all	ANA/PED/STEP/SAMP/results/variants/diploidSV.vcf.gz.tbi	SAVE/PED/SAMP	SAMP.manta.diploidSV.vcf.gz.tbi

#--------------#
# multmanta    #
#--------------#
multmanta	NA	nsped	all	ANA/PED/STEP/results/variants/diploidSV.vcf.gz	SAVE/PED	PED.manta.diploidSV.vcf.gz
multmanta	NA	nsped	all	ANA/PED/STEP/results/variants/diploidSV.vcf.gz.tbi	SAVE/PED	PED.manta.diploidSV.vcf.gz.tbi

#--------------#
# clinsv       #
#--------------#
clinsv	NA	wgs	all	ANA/PED/STEP/SAMP/SVs/joined/SV-CNV.RARE_PASS_GENE.vcf	SAVE/PED/SAMP	SAMP.clinsv.SV-CNV.RARE_PASS_GENE.vcf

#--------------#
# exdepth      #
#--------------#
exdepth	NA	wes	all	ANA/cnv/APP/STEP/SAMP/SAMP.exdepth.CNVs.tsv	SAVE/PED/SAMP	SAMP.exdepth.CNVs.tsv

#--------------#
# freec        #
#--------------#
freec	NA	wgs	all	ANA/PED/STEP/SAMP/5000/SAMP.freec.5000.p.value.txt	SAVE/PED/SAMP	SAMP.freec.5000.p.value.txt
freec	NA	wgs	all	ANA/PED/STEP/SAMP/20000/SAMP.freec.20000.p.value.txt	SAVE/PED/SAMP	SAMP.freec.20000.p.value.txt
freec	NA	wgs	all	ANA/PED/STEP/SAMP/50000/SAMP.freec.50000.p.value.txt	SAVE/PED/SAMP	SAMP.freec.50000.p.value.txt
freec	NA	wes	all	ANA/PED/STEP/SAMP/0/SAMP.freec.0.p.value.txt	SAVE/PED/SAMP	SAMP.freec.0.p.value.txt

#--------------#
# somalier     #
#--------------#
somalier	NA	nsana	all	ANA/STEP/SAMP.somalier	SAVE/PED/SAMP	SAMP.somalier

#--------------#
# bamtocram    #
#--------------#
bamtocram	NA	no	all	ANA/PED/STEP/SAMP/SAMP.cram	SAVE/PED/SAMP	SAMP.cram
bamtocram	NA	no	all	ANA/PED/STEP/SAMP/SAMP.cram.crai	SAVE/PED/SAMP	SAMP.cram.crai
