#--------------#
# singshortvar #
#--------------#
singshortvar	ANA/PED/STEP
singshortvar	ANA/PED/gathervcfpreannot
singshortvar	ANA/PED/hapcallgenonorm

#--------------#
# mt           #
#--------------#
mt	ANA/PED/STEP

#--------------#
# roh          #
#--------------#
roh	ANA/PED/STEP

#--------------#
# allshortvar #
#--------------#
allshortvar	ANA/STEP

#--------------#
# multshortvar #
#--------------#
multshortvar	ANA/PED/STEP

#--------------#
# singmanta    #
#--------------#
singmanta	ANA/PED/STEP

#--------------#
# multmanta    #
#--------------#
multmanta	ANA/PED/STEP

#--------------#
# clinsv       #
#--------------#
clinsv	ANA/PED/STEP

#--------------#
# exdepth      #
#--------------#
exdepth	ANA/cnv/*/STEP

#--------------#
# freec        #
#--------------#
freec	ANA/PED/STEP

#--------------#
# smafind      #
#--------------#
smafind	ANA/PED/STEP

#--------------#
# smncall      #
#--------------#
smncall	ANA/PED/STEP

#--------------#
# cyrius       #
#--------------#
cyrius	ANA/PED/STEP

#--------------#
# gauchian     #
#--------------#
gauchian	ANA/PED/STEP

#--------------#
# pypgx        #
#--------------#
pypgx	ANA/PED/STEP

#--------------#
# stripy       #
#--------------#
stripy	ANA/PED/STEP

#--------------#
# ehshort      #
#--------------#
ehshort	ANA/PED/STEP

#--------------#
# ehlong       #
#--------------#
ehlong	ANA/PED/STEP

#--------------#
# hlahd        #
#--------------#
hlahd	ANA/PED/STEP

#--------------#
# hlakir       #
#--------------#
hlakir	ANA/PED/STEP

#--------------#
# somalier     #
#--------------#
somalier	ANA/STEP
somalier	ANA/PED/STEP

#--------------#
# mosdepth     #
#--------------#
mosdepth	ANA/PED/STEP

#--------------#
# igvcram      #
#--------------#
igvcram	ANA/PED/STEP

#--------------#
# bamtocram    #
#--------------#
bamtocram	ANA/PED/STEP
