singshortvar	*/singshortvar
singshortvar	*/hapcallgenonorm
singshortvar	*/gathervcfpreannot
mt	*/mt
roh	*/roh
roh	*/hapcallgenonorm
roh	*/gathervcfpreannot
allshortvar	allshortvar
allshortvar	*/hapcallgenonorm
multshortvar	*/multshortvar
multshortvar	*/hapcallgenonorm
singmanta	*/singmanta
multmanta	*/multmanta
clinsv	*/clinsv
exdepth	cnv/*/exdepth
freec	*/freec
smafind	*/smafind
smncall	*/smncall
cyrius	*/cyrius
gauchian	*/gauchian
pypgx	*/pypgx
stripy	*/stripy
ehshort	*/ehshort
ehlong	*/ehlong
hlahd	*/hlahd
hlakir	*/hlakir
somalier	somalier
somalier	*/somalier
mosdepth	*/mosdepth
igvcram	*/igvcram
bamtocram	*/bamtocram
gutierrezsarprs	*/gutierrezsarprs
tegerpgxgeno	*/tegerpgxgeno
