#taskName	taskDef	taskStep
launch	launch pipeline	any step
check	check job status, error and outputs	any step
qc	check QC metrics	any step
copy	copy final outputs into results folder	any step
copyReport	copy SNVs/INDELs report to be signed (production analysis only)	singshortvar
copyGPAP	copy outputs for GPAP submission	roh,exdepth,freec,singmanta,ehshort,ehlong,igvcram
casesumm	case summarizer from results folder	singshortvar,roh,mt,cyrius,pypgx,smafind,smncall,ehshort,singmanta
purge	purge working folders for re-launching purpose (can be restricted by -b parameter)	any step
clean	clean working folders (including intermediate file-saving process)	any step
email	generate email draft with step(s) description	any step
time	get analysis time	no step required
tar	tar analysis folder	no step required
