hapcallgenonorm_tt="hapcallgenonorm.tt"
annotshortvar_tt="annotshortvar.tt"
bamtocram_tt="bamtocram.tt"
bcfnorm_tt="bcfnorm.tt"
combgvcf_tt="combgvcf.tt"
genogvcf_tt="genogvcf.tt"
hapcall_tt="hapcall.tt"
multmanta_tt="multmanta.tt"
gathervcf_tt="gathervcf.tt"
mosdepth_tt="mosdepth.tt"
singshortvar_tt="singshortvar.tt"
allshortvar_tt="allshortvar.tt"
multshortvar_tt="multshortvar.tt"
somalier_tt="somalier.tt"
somext_tt="somext.tt"
somrel_tt="somrel.tt"
tagfilt_tt="tagfilt.tt"
exdepth_tt="exdepth.tt"
exdepthprep_tt="exdepthprep.tt"
exdepthlink_tt="exdepthlink.tt"
exdepthrun_tt="exdepthrun.tt"
freecprep_tt="freecprep.tt"
freecrun_tt="freecrun.tt"
singmanta_tt="singmanta.tt"
smafind_tt="smafind.tt"
smncall_tt="smncall.tt"
vcf2tab_tt="vcf2tab.tt"
roh_tt="roh.tt"
intervarappend_tt="intervarappend.tt"
spliceairun_tt="spliceairun.tt"
spliceaiappend_tt="spliceaiappend.tt"
fakeappend_tt="fakeappend.tt"
mt_tt="mt.tt"
reportmake_tt="reportmake.tt"
hardfilt_tt="hardfilt.tt"
clinsv_tt="clinsv.tt"
cyrius_tt="cyrius.tt"
gauchian_tt="gauchian.tt"
pypgx_tt="pypgx.tt"
stripy_tt="stripy.tt"
expansionhunter_tt="expansionhunter.tt"
hlahd_tt="hlahd.tt"
hlakir_tt="hlakir.tt"
t1k_tt="t1k.tt"
igvcram_tt="igvcram.tt"
spliceairuncandigene_tt="spliceairuncandigene.tt"
gutierrezsarprs_tt="gutierrezsarprs.tt"
tegerpgxgeno_tt="tegerpgxgeno.tt"

